### ISSUE TITLE
Questions about applying PopArt on OPRE

### ISSUE THREAD

**Issue by kinalmehta** [deepmind/meltingpot#100]
Hi,

I noticed that the PopArt layer is applied on the value head of the models in Meltingpot v2.0. I was able to implement it on IMPALA successfully, but when applying it to OPRE, there seems to be some issue, and the model never converges.
I implemented it using the following reference: https://github.com/deepmind/rlax/blob/master/examples/pop_art.py.

The structure of OPRE uses a mixture of n different models where n​ is the options dimension. Given that we have only one return value, how exactly are the weights of those n​ different value heads being handled?

**Option 1:**
- apply popart_update on n​ different models n​ times
- but the challenge here is that if I use n​ separate popart states for all n​ different models, which values should be used to normalize the final targets
- and if we use a single popart state, it'll get updated n​ different times while updating the weights of n​ models

**Option 2:**
- use a single feed-forward layer with n​ different outputs
- apply popart_update normally as usually done on layers with a single output

Tried both methods, and the loss values go to nan​ in both cases.
How exactly are you guys implementing this?

Thanks
Kinal

**Comment by vezhnick** [comment]
The way to apply popArt to OPRE, in my experience, is to simply apply it to the resulting mixture (the final sum).
I think in the original paper the fiddle with the linear layer that produces the baseline values, but you can simply "whiten" the value function by learning the shift, the scale and the second moment.

**Comment by kinalmehta** [comment]
Thanks for the response. 

I implemented the version you mentioned, and it is working fine. 
Also, I figured that the issue of `nan` was because I used a smaller batch size than the one mentioned in the paper. Tuning the $\epsilon$ parameter for RMSprop and setting it to `1e-2` instead of `1e-5` helped stabilize the learning. 

Closing this as it seems to be solved now.
