### ISSUE TITLE
Problems running examples/rllib/view_models.py

### ISSUE THREAD

**Issue by ninell-oldenburg** [deepmind/meltingpot#110]
Hi,

I've tried training examples on different environments, e.g., `commons_harvest__open` and `clean_up` but I am running into the following error when trying to execute `view_models.py`

```
File "/Users/nell/Documents/GitHub/social-contracts/examples/rllib/utils.py", line 183, in initial_state
    return self._model.get_policy(self._policy_id).get_initial_state()
AttributeError: 'NoneType' object has no attribute 'get_initial_state'
```

As `self._policy_id` is coming out as `"av"`, I've also tried setting it to the current version of ray's [`sample_batch.py`](https://github.com/ray-project/ray/blob/80e982b17aa20ad9f6be16704a0a654ba72d4218/rllib/policy/sample_batch.py#L27) `"default_policy"` but nothing changed.

It's running on
MacOs M1 chip
Python 3.10.8
Ray version 2.0.0

Thank you in advance!

**Comment by Muff2n** [comment]
This is because view_models is loading a hardcoded policy "av". Now that self_play_train.py has changed to name policies `f"agent_{i}"`, where i is `substrate.get_config(substrate_name).default_player_roles,` this line will need to be updated to reflect that change.
