### ISSUE TITLE
ModuleNotFoundError: No module named 'meltingpot.python'

### ISSUE THREAD

**Issue by elliottower** [deepmind/meltingpot#119]
GitHub workflow with this error: https://github.com/Farama-Foundation/Shimmy/actions/runs/4441939882/jobs/7797630023?pr=39

I've gotten this error a few times when running the code locally in the past few weeks, and am not sure exactly what I did to fix it. It has worked in the past with our github workflows and docker images but now seems to be broken. I am using it to get the list of substrates and call substrate.get_config() and substrate.build(): 
https://github.com/elliottower/Shimmy/blob/main/tests/test_meltingpot.py#L10

Being outward facing functions intended to be used to initialize environments I would think these should definitely not raise errors. Thinking maybe if the __init__.py explicitly imported them it may fix the problem? 

I am able to import meltingpot itself perfectly fine but when I try to call functions in the submodule meltingpot.python it either gives an error that meltingpot.python is not found or if I try to import it then it will sometimes fail as I've said above. I don't think it's actually stochastic it's just due to me changing the dockerfiles/environment over time to try and work out other unrealted issues, and some of those configurations evidently making this import fail.

**Comment by Viswesh-N** [comment]
Try the following, this resolved the error for me:
`cd <directory_to_meltingpot>`
`export PYTHONPATH=$(pwd)`

**Comment by jagapiou** [comment]
I don't think I can be much help here I'm afraid.

I suspect that if you put `import meltingpot.python ...` in `meltingpot/__init__.py` you'd have the same issue. But I guess try it and see.

My guess is it's something to do with your PYTHONPATH or what directory you are running you are running the tests from. This may help? https://stackoverflow.com/questions/54895002/modulenotfounderror-with-pytest

**Comment by elliottower** [comment]
I found this previous PR and then in the README there's a note about the pythonpath variable, although I think it's best practice to extend it rather than overwrite it: https://askubuntu.com/a/250935

**Comment by elliottower** [comment]
I was able to get it to work by adding these lines to the dockerfile:
```
# Download assets
RUN mkdir -p /workspaces/meltingpot/meltingpot && \
  curl -SL https://storage.googleapis.com/dm-meltingpot/meltingpot-assets-2.1.0.tar.gz \
  | tar -xz --directory=/workspaces/meltingpot/meltingpot

# Clone meltingpot repository
RUN git clone https://github.com/deepmind/meltingpot.git
RUN cp -r /meltingpot/ /workspaces/meltingpot/ && rm -R /meltingpot/

# Install meltingpot dependencies
WORKDIR /workspaces/meltingpot/meltingpot/

RUN pip install .

# Set Python path for meltingpot
ENV PYTHONPATH=${pwd}
```

As a random note, the base requirement for tensorflow should probably be moved to an optional requirement, as the README shows how you can install tensorflow or pettingzoo as optional dependencies, but when you run pip install -e . it still installs tf.

**Comment by jagapiou** [comment]
Glad you got it working :-)

FYI `tensorflow` is a required dep for meltingpot as the Bots in the Scenarios are tf.SavedModels.
