### ISSUE TITLE
Problem installing dmlab2d for M2 arm64

### ISSUE THREAD

**Issue by jonathan-cook235** [deepmind/meltingpot#122]
The README states that there is no appropriate wheel for the Apple M1/M2 chipset. It provides an example bash script for installing and setting up the wheel, but this results in an error when trying to import dmlab2d_pybind.so, saying that the version installed was still 'x86_64' rather than 'arm64'. I'm unsure what to change about the bash script to get the right version installed.

**Comment by jagapiou** [comment]
I can't help I'm afraid: I think this is an issue with your setup. The bash script works fine on my arm64 mac, and in our tests. My guess is that you have the `x86_64` version of Bazel and not the `arm64` version (or XCode or some other part of your toolchain).

Here's what my mac says:
```
$ bazel version
WARNING: Invoking Bazel in batch mode since it is not invoked from within a workspace (below a directory having a WORKSPACE file).
Build label: 5.3.2
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 19 18:35:48 2022 (1666204548)
Build timestamp: 1666204548
Build timestamp as int: 1666204548
```
