### ISSUE TITLE
ImportError: cannot import name 'BaseParallelWrapper' from 'pettingzoo.utils'

### ISSUE THREAD

**Issue by nkenschaft** [deepmind/meltingpot#128]
After following the installation instructions, I encounter the error in the title when trying to run the `sb3_train.py` script. I've tried multiple Python versions (3.9 & 3.10), reinstalling pettingzoo, etc, but nothing seems to work. Any help would be appreciated. Thanks!

**Comment by nkenschaft** [comment]
Turns out it's a typo (`BaseParallelWrapper` vs `BaseParallelWraper`) upstream in the PettingZoo repo. For anyone else who encounters this, it looks like someone is working on fixing it, so you can either wait for just go fix the typo yourself.

**Comment by vcis-wangchenxu** [comment]
I have the same question. Have you solved the problem

**Comment by nkenschaft** [comment]
As a quick and dirty fix, running `find . -type f -exec sed -i 's/BaseParallelWraper/BaseParallelWrapper/g' {} +` in the root directory of the project appears to do the trick. It's a bit hacky but it works until FaramaFoundation fixes PettingZoo.
