### ISSUE TITLE
Setting a random seed

### ISSUE THREAD

**Issue by ninell-oldenburg** [deepmind/meltingpot#129]
Hi!

I'm trying to find a place to set a random seed for the initial substrate setting. However, all places I've tried so far seem to do it, and I was wondering if an interface exists anywhere in the code.

Things I've tried:
- [`meltingpot/lua/modules/api_factory.lua`](https://github.com/deepmind/meltingpot/blob/df1be36229c00a8e2933f85de77fe827f26f2ffa/meltingpot/lua/modules/api_factory.lua#L38) + removing `random:seed()` calls
- [`meltingpot/python/configs/substrates/clean_up.py`](https://github.com/deepmind/meltingpot/blob/df1be36229c00a8e2933f85de77fe827f26f2ffa/meltingpot/python/configs/substrates/clean_up.py#L842) (as an example) + adding an `env_seed` to the `build()` function.
- [`meltingpot/python/substrate.py`](https://github.com/deepmind/meltingpot/blob/main/meltingpot/python/substrate.py#L32) + adding an `env_seed` to the build function + all dependencies.

Thanks in advance!

**Comment by jagapiou** [comment]
There are multiple random seeds:

1. `dmlab2d.Lab2d` (pybind C++) takes a seed in the `lab2d_settings_dict` that is passed to Lua (see [here](https://github.com/deepmind/meltingpot/blob/main/meltingpot/python/utils/substrates/builder.py)).
2. [`dmlab2d.Environment`](https://github.com/deepmind/lab2d/blob/main/dmlab2d/__init__.py) takes a seed for it's Python/C++

Both should be controllable by the [`env_seed` argument](https://github.com/deepmind/meltingpot/blob/main/meltingpot/python/utils/substrates/builder.py). However, [this isn't wired in](https://github.com/deepmind/meltingpot/blob/main/meltingpot/python/utils/substrates/substrate.py).

I've discussed this at https://github.com/deepmind/meltingpot/issues/113#issuecomment-1462212082 there may be more relevant info there on what solution to take (e.g. `seed` in a config, as an override to `build`, as an argument to `reset()`).

**Comment by ninell-oldenburg** [comment]
Amazing, thank you! Wired it in.
