### ISSUE TITLE
devcontainer installation

### ISSUE THREAD

**Issue by alexunderch** [deepmind/meltingpot#147]
When installing `meltingpot` using .devcontainer, an error pops:
`ERROR: dmlab2d-1.0-cp39-cp39-manylinux_2_35_x86_64.whl is not a supported wheel on this platform.`
After some googling, I found out that `2_35` wheel tag is compatible with ubuntu22.04 and later ([source](https://github.com/mayeut/pep600_compliance)). 

Is there a way to use pip wheels in ubuntu20.04, or version in the dockerfile should be upgraded to 22.04?

**Comment by jagapiou** [comment]
Thanks for the heads up, I'll update the Dockerfile.
