### ISSUE TITLE
Running ACB Baseline

### ISSUE THREAD

**Issue by AsadJeewa** [deepmind/meltingpot#162]
How can I run the ACB baseline? self_play_train.py runs PPO and says "The ACB models used as baselines in the meltingpot paper were not run using rllib". I would like to run ACB on a modified version of cleanup. Thanks

**Comment by duenez** [comment]
We don't have an open source implementation of the ACB baseline, and it would be hard to open source, as it relies on significant internal tooling and infrastructure. We anticipate some async actor critic methods will be provided as part of the [Melting Pot Competition](https://twitter.com/coop_ai/status/1664270352435015683). Those will not be our internal implementation, but will be good reference points for open source RL baselines on Melting Pot. So, stay tuned! :)
