### ISSUE TITLE
Use extras in setup.py

### ISSUE THREAD

**Issue by jkterry1** [deepmind/meltingpot#18]
Right now, setup.py includes tensorflow as a main dependency. The problem with specifying tensorflow as a main dependency is that if you're trying to use jax or pytorch with the environments alone its an unnecessary dependency that can be problematic to install (which is what I'm doing), and even if you want to use tensorflow you often want to custom install tensorflow-gpu or build it from source or something. This in turn means that in these reasonably common cases, you have to use --no-deps on installation and do everything manually, which is bad practice and impedes reproducibility. The standard way other libraries handle situations like this (gym, rlcard, etc) is to use the extras feature in setup.py files, such that only the dependencies files for the environments are installed by default, and extra arguments can be passed for other decencies (you could call them examples, tests, etc.)

**Comment by duenez** [comment]
Hello, thank your for you message and suggestion. Yes, we could make tensorflow an `extras` dependency, but it is likely required for SavedModel, and thus, to run the scenarios. You are right that we likely don't need it just for training on substrates.

We'll evaluate this and get back to you soon.

Thanks!

**Comment by jagapiou** [comment]
Sorry meant to ask if that workaround would work for your use case?

We'd prefer both substrates (training envs) and scenarios (test envs) to work on a simple install, but if you have a substrate-only use case perhaps we can have some optional minimal install without tensorflow?
