### ISSUE TITLE
Conversion from dm_env to gym space

### ISSUE THREAD

**Issue by semitable** [deepmind/meltingpot#2]
Hi all!

I've spotted a small issue in `examples/rllib/multiagent_wrapper.py` and specifically in the `_spec_to_space` function.

https://github.com/deepmind/meltingpot/blob/ef3353dc4eee23d8a4b473b63dd189ac4612bd48/examples/rllib/multiagent_wrapper.py#L53-L56

In this part of the code, `spec` is first checked if it's an instance of a `BoundedArray` and then `DiscreteArray`. However, from dm_env, DiscreteArray is a subclass of BoundedArray:
```python 
class DiscreteArray(BoundedArray):
```
That means when comparing a DiscreteArray, the first check will be true, and the function returns a Box (instead of Discrete). 

I encountered this when converting the action space of `allelopathic_harvest` but I assume that's the case for the rest of the environments.

The obvious solution would be to swap the if statement, but I am not using rllib so I can't say for sure if it would break something. I am surprised it works in the first place. Maybe rllib knows to convert an integer Box space to a discrete space (?).

**Comment by duenez** [comment]
Thank you, this should be fixed at head, now!
