### ISSUE TITLE
Building problems in Ubuntu 18.04

### ISSUE THREAD

**Issue by ElChenteFernandez** [deepmind/meltingpot#29]
Hello, 

I am trying to install meltingpot in my Ubuntu18.04 machine.

When I run `./install.sh` I got the following error message 
`
ERROR: dmlab2d-1.0-cp38-cp38-manylinux_2_27_x86_64.whl is not a supported wheel on this platform.`

I am using a conda environment with python version: `Python 3.7.0`
gcc version: `gcc (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0`
bazel: `bazel 5.1.1`

How can I fix this ?

**Comment by jagapiou** [comment]
That seems like the wrong wheel (3.8) for your 3.7 platform.

Are you using the latest version of `install.sh`?

**Comment by ElChenteFernandez** [comment]
Yes,  I am using the latest version, 
I noticed that after lab2d is populated the path `meltingpot/lab2d/bazel-bin/dmlab2d` contains multiple wheels.

```
dmlab2d-1.0-cp37-cp37m-manylinux_2_27_x86_64.whl
dmlab2d-1.0-cp37-cp37m-manylinux_2_27_x86_64.whlname
dmlab2d-1.0-cp38-cp38-manylinux_2_27_x86_64.whl
dmlab2d-1.0-cp38-cp38-manylinux_2_27_x86_64.whlname
```

Since install.sh uses `pip install lab2d/bazel-bin/dmlab2d/dmlab2d-*.whl` it installs everything which causes the issue
I changed the line to `pip install lab2d/bazel-bin/dmlab2d/dmlab2d-1.0-cp37*.whl` and it solved the issue

**Comment by jagapiou** [comment]
Glad it got sorted :-)

For me it only created the one wheel. Is it possible you ran the dmlab2d wheel builder previously but for Python 3.7? I should probably add some kind of tempfile in there to ensure that repeated runs of install.sh are independent.

**Comment by jagapiou** [comment]
I think `pip install --find-links=lab2d/bazel-bin/dmlab2d dmlab2d` should ensure `pip` selects the wheel itself, I'll update `install.sh`.

**Comment by jagapiou** [comment]
Updated in 383321d78a8b2b540456f98c4352492022f46050
