### ISSUE TITLE
RLlib example utils.py error

### ISSUE THREAD

**Issue by GoingMyWay** [deepmind/meltingpot#34]
Hi, I think https://github.com/deepmind/meltingpot/blob/main/examples/rllib/utils.py#L28

```python
from meltingpot.python import bot
```

should be changed to the following line

```python
from meltingpot.python.utils.bots import policy as bot
```

The current code reports error.

**Comment by duenez** [comment]
You are right, we did a bit of refactoring of these files, and this example got left behind. Thanks for the catch!
