### ISSUE TITLE
Dear authors, will you plan to release the training curves?

### ISSUE THREAD

**Issue by GoingMyWay** [deepmind/meltingpot#37]
Dear authors, 

Thanks for the great contribution to the MARL community. Melting Pot provides a great set of evaluation scenarios for MARL research. In your paper, we can find many convincing results both in the main text and the appendix. It would be great if you can also put training curves as well as evaluation curves (like many Atari/mujoco RL papers) since it can help researchers to check how many training timesteps we need to get some specific level of performance.  It is my humble suggestion, thank you!

Best regards,
A Melting Pot user

**Comment by jzleibo** [comment]
This is a great idea, and you have good timing :). I don't see any reason why we couldn't do it for the next release, which we are preparing now. We are re-running all the baselines anyway.

**Comment by GoingMyWay** [comment]
> This is a great idea, and you have good timing :). I don't see any reason why we couldn't do it for the next release, which we are preparing now. We are re-running all the baselines anyway.

Cool. Thank you!
