### ISSUE TITLE
[Feature] Explicitly force bots in scenarios to use CPUs

### ISSUE THREAD

**Issue by GoingMyWay** [deepmind/meltingpot#38]
Hi, all. For the saved TF models, when using GPUs, it will raise errors:

```
2 root error(s) found.
  (0) UNIMPLEMENTED:  The Conv2D op currently only supports the NHWC tensor format on the CPU. The op was given the format: NCHW
	 [[{{node learner_agent/step/encoder/pixels_encoder/conv_2d_0/convolution}}]]
	 [[StatefulPartitionedCall/StatefulPartitionedCall/learner_agent/step/encoder/pixels_encoder/Relu_1/_6]]
  (1) UNIMPLEMENTED:  The Conv2D op currently only supports the NHWC tensor format on the CPU. The op was given the format: NCHW
	 [[{{node learner_agent/step/encoder/pixels_encoder/conv_2d_0/convolution}}]]
0 successful operations.
0 derived errors ignored.
	 [[StatefulPartitionedCall]]
```

My suggestion is when creating scenarios, we can forcely set CPU for TensorFlow. 
```python
tf.config.set_visible_devices([], 'GPU')
```

It works for TF 2.1+. Thank you!

**Comment by duenez** [comment]
We recently changed the inference to use GPU is available. Internally this didn't fail. Might be a version incompatibility? John could you check?

**Comment by jagapiou** [comment]
In 9b922e9ddfda2eb447449f7e38fba515255402c0 I specified a `DistributionStrategy` for bots that defaults to CPU. Does that not work?

**Comment by GoingMyWay** [comment]
> In [9b922e9](https://github.com/deepmind/meltingpot/commit/9b922e9ddfda2eb447449f7e38fba515255402c0) I specified a `DistributionStrategy` for bots that defaults to CPU. Does that not work?

Thanks. Maybe there was an implicit behaviour that caused the issue. I will check it and try to find the reason.
