### ISSUE TITLE
Substrate tutorial

### ISSUE THREAD

**Issue by ManuelRios18** [deepmind/meltingpot#42]
Hello, 
I think that there is a minor issue in the substrate tutorial when I run:
`python3 meltingpot/examples/tutorial/harvest/play_harvest.py --observation WORLD.RGB --display_text`
I got an index out of range in:

```
line 317, in run_episode
    player_prefix = player_prefixes[player_index]
```
I fresh installed meltingpot  yesterday.

Anyway, the finished example works perfectly, is just the blank project

**Comment by duenez** [comment]
Thanks for letting us know! We have an internal fix that will be getting pushed here shortly.
