### ISSUE TITLE
Installation frozen

### ISSUE THREAD

**Issue by yesfon** [deepmind/meltingpot#53]
Hello,

I am trying to install meltingpot on my ubuntu 20.04 machine, these are my conda, python and bazel versions:

- conda: 4.12.0
- Python 3.9.11
- bazel 5.2.0
- (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

The installation freezes as shown in the screenshot. I left the installation overnight and it still does not progress.

![image](https://user-images.githubusercontent.com/102532937/176475950-fbf5268c-b4ce-488e-b7fc-03954228709c.png)

**Comment by jagapiou** [comment]
It froze on the tests. Hopefully those would have passed, but it is installed.
