### ISSUE TITLE
macOS Apple M1 Chip Support

### ISSUE THREAD

**Issue by GoingMyWay** [deepmind/meltingpot#6]
Hi, while running test scripts on macOS Apple M1 Chip. An error occurred:

```
$ python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
creating dm_meltingpot.egg-info
writing dm_meltingpot.egg-info/PKG-INFO
writing dependency_links to dm_meltingpot.egg-info/dependency_links.txt
writing requirements to dm_meltingpot.egg-info/requires.txt
writing top-level names to dm_meltingpot.egg-info/top_level.txt
writing manifest file 'dm_meltingpot.egg-info/SOURCES.txt'
reading manifest file 'dm_meltingpot.egg-info/SOURCES.txt'
writing manifest file 'dm_meltingpot.egg-info/SOURCES.txt'
running build_ext
[1]    96188 illegal hardware instruction  python3 setup.py test
```

Does it mean MeltingPot cannot run on macOS Apple M1 Chip?

**Comment by jagapiou** [comment]
Hi just to check:

1. Did you follow https://github.com/deepmind/meltingpot#installation?
2. Did the `dmlab2d` tests pass?
3. What version of macOS are you using?

**Comment by jagapiou** [comment]
Looking at `dmlab2d` I see only x86 wheels: https://github.com/deepmind/lab2d/releases/tag/release_candidate_2021-07-13 so I guess the issue is you used one of those. You will have to build your own wheel for `dmlab2d` using:
```sh
bazel build -c opt --define=lua=5_1 //dmlab2d:dmlab2d_wheel
```

See [install.sh](https://github.com/deepmind/meltingpot/blob/main/install.sh) for how this can be done.

**Comment by jagapiou** [comment]
I've spoken to the `dmlab2d` team about adding M1 wheels, and we're looking into it. But I suggest building yourself for now.

**Comment by GoingMyWay** [comment]
> Looking at `dmlab2d` I see only x86 wheels: https://github.com/deepmind/lab2d/releases/tag/release_candidate_2021-07-13 so I guess the issue is you used one of those.
> 
> I've spoken to the `dmlab2d` team about adding M1 wheels, and we're looking into it.
> 
> For now you will have to build your own wheel for `dmlab2d` using:
> 
> ```shell
> bazel build -c opt --define=lua=5_1 //dmlab2d:dmlab2d_wheel
> ```
> 
> See [install.sh](https://github.com/deepmind/meltingpot/blob/main/install.sh) for how this can be done.

Thank you very much. I will build the `dmlab2d`.
