### ISSUE TITLE
Calculating the reward in * in the matrix substrates.

### ISSUE THREAD

**Issue by GoingMyWay** [deepmind/meltingpot#80]
Dear authors, 

I have a question on calculating the reward of each timesteps of * in the matrix substrates. For example chicken_in_the_matrix, the matrix for the interaction is (copied from the paper):

$$
A_{row} = A^{T}_{col}= \left[\begin{array}{cc}
3 & 2\\
5 & 0
\end{array}\right]
$$

Give inventories $v_1=$`[1 1]` for agent 1 and $v_2=$`[1 3]` for agent 2 in an interaction. How can I calculate the reward $r_1$ for agent 1  and reward $r_2$ for agent 2? I check the OPRE paper and found the following equation:

$$
r_0 = \frac{v_0}{||v_0||}M(\frac{v_1}{||v_1||})^{T}=-r_1
$$

where $M=A_{row} = A^{T}_{col}$.

Can it be applied for chicken_in_the_matrix?

Thank you very much!

**Comment by duenez** [comment]
Yes, you can use the same formula, except that, since this is not zero sum, $r_0$ is not the same as $-r_1$. Instead, $r_1 = \frac{v_1}{||v_1||} A_{col} \left( \frac{v_0^T}{||v_0||} \right)$.
