### ISSUE TITLE
Melting Pot Version 2.0.0

### ISSUE THREAD

**Issue by jagapiou** [deepmind/meltingpot#81]
We are currently preparing the codebase for the next Melting Pot release, in which we will release new substrates and scenarios.

All this work will be done at `HEAD` on `main`, but we will keep the v1 substrates and scenarios working and unchanged up until we release v2.0.0.

However, there will likely be some disruption during this process (e.g. API changes, file moves). To avoid this please use tagged release [v1.0.4](https://github.com/deepmind/meltingpot/releases/tag/v1.0.4).

**Comment by GoingMyWay** [comment]
> We are currently preparing the codebase for the next Melting Pot release, in which we will release new substrates and scenarios.
> 
> All this work will be done at `HEAD` on `main`, but we will keep the v1 substrates and scenarios working and unchanged up until we release v2.0.0.
> 
> However, there will likely be some disruption during this process (e.g. API changes, file moves). To avoid this please use tagged release [v1.0.4](https://github.com/deepmind/meltingpot/releases/tag/v1.0.4).

@jagapiou Thank you John. Thanks for the great efforts made by your team to make the new Melting Pot.

**Comment by jagapiou** [comment]
[v2.0.0](https://github.com/deepmind/meltingpot/releases/tag/v2.0.0) is released!

There will likely be a few maintenance patches over the next few weeks to deal with things like https://github.com/deepmind/meltingpot/issues/84.

In addition, we intend to add a few more substrates, an evaluation tool and some raw data.

**Comment by kinalmehta** [comment]
Hi,

The changes for v2.0 include "Removed all v1 scenarios, bots, and substrates and replaced with new versions." as one of the points. Is there any comparison of the changes between v1 and v2 of meltingpot as most of the environments seem to be quite similar to those on v1 (e.g. Clean-up, Running with scissors in the matrix, etc)

Thanks
Kinal Mehta

**Comment by jzleibo** [comment]
Hi Kinal,

We don't have a point-by-point comparison for the entire suite. Most of the changes are additions of new substrates and scenarios. 

For some of the older substrates the changes are purely cosmetic, e.g. clean_up, territory, and allelopathic_harvest. For commons_harvest we improved the graphics and also made the maps smaller and used less players (7 versus 12). For *_in_the_matrix substrates we added the "ready to interact" mechanic, which resolves some issues with the old version and makes things more unified across all substrates in the *_in_the_matrix family.

We did retrain all the background population bots for all the scenarios, so their performance may have shifted somewhat. You should expect all scenarios that still have the same description to work the same way though.

But please ask here if there are more detailed questions about specific substrates or scenarios, I can dig out any such info you might need.

**Comment by kinalmehta** [comment]
Thanks for these details. I don't have any specific questions as of now.
I was asking this to understand how it would affect results in my codebase if I directly swap in v1 environments with v2. I believe it doesn't affect the self-play training in the scenarios you explained. 

Thanks again for this awesome environment suite.
