### ISSUE TITLE
Horizon setting in examples

### ISSUE THREAD

**Issue by IpadLi** [deepmind/meltingpot#9]
Hi @jzleibo , in the self_play_train.py in examples, is there any suggestion for setting the config parameters:

num_workers = 1
rollout_fragment_length = 30
train_batch_size = 200
horizon = 200

The horizon is set to 200, but the "allelopathic_harvest" scenario lasts 2000 steps. Why not set the horizon to 2000?

**Comment by duenez** [comment]
This was an oversight on our part. A fix is in flight. Thanks for pointing it out!
